export const fakeContent = (): string => {
  return `
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin fermentum id purus sed aliquam. In eget enim gravida, vulputate magna ut, convallis tortor. Cras id libero aliquet velit cursus pulvinar. Sed finibus fringilla orci, varius ullamcorper nisl vehicula vestibulum. Vestibulum venenatis tortor ut risus sodales, a convallis lacus molestie. Mauris ac placerat dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum mauris magna, gravida et quam nec, mollis ultricies sem.

Etiam faucibus vestibulum velit nec auctor. Nunc mollis accumsan mauris vitae interdum. Nulla cursus vulputate velit, at sollicitudin magna fermentum sed. Nam porta, augue in malesuada finibus, libero elit dictum massa, eget blandit eros purus sit amet sem. Pellentesque cursus aliquam blandit. Nam elementum aliquam nunc at volutpat. Maecenas vitae elementum elit. Vivamus bibendum, ligula non aliquet iaculis, tortor nibh facilisis tortor, quis ullamcorper risus velit ut lectus. Duis consectetur a magna vitae eleifend. Ut et ex magna. Phasellus pulvinar semper orci eu tristique. Pellentesque sed erat finibus, sagittis enim et, gravida augue. Vivamus pellentesque ipsum id est sagittis imperdiet. Sed gravida, dolor sed volutpat posuere, purus tellus gravida ex, eu ornare lorem libero ornare felis. Integer tempor eros vitae eros suscipit, semper porttitor dolor imperdiet. Phasellus sem massa, volutpat et interdum sit amet, tristique et dui.

Proin ac mauris vel lacus dapibus aliquet. Praesent ac neque sit amet augue consequat volutpat. Morbi tincidunt ex a condimentum imperdiet. Suspendisse non mattis nisi. Cras sagittis blandit nunc sed volutpat. Nullam vel pulvinar dolor, quis pulvinar libero. Sed mollis ante nisi, et pulvinar risus fermentum in. Maecenas tristique lacus a mi venenatis aliquet. Fusce a nunc vehicula, malesuada eros non, venenatis est. Aliquam eget ipsum mi. Aliquam ultrices orci id magna congue luctus.
    `;
};
